create or replace function dwh_staging.sf_prepare_sap_debit_credit_bill()
    returns void
    language plpgsql
as
$$
begin

    truncate table dwh_staging.report_debit_credit_bill;
    truncate table dwh_presentation.report_debit_credit_bill;

    insert into dwh_staging.report_debit_credit_bill
    select nullif('UT12', '') as p_stat,
           nullif(buzei, '') as buzei,
           nullif(belnr, '') as belnr,
           nullif(gjahr, '')  as gjahr,
           nullif(hdr_txt, '') as hdr_txt,
           nullif(clr_belnr, '') as clr_belnr,
           nullif(bp_group, '') as bp_group,
           nullif(n_bp_group, '') as n_bp_group,
           nullif(partner, '') as partner,
           nullif(n_partner, '') as n_partner,
           to_date(nullif(zuonr_ext_date, ''), 'YYYY-MM-DD') as zuonr_ext_date,
           nullif(zuonr_int_number, '') as zuonr_int_number,
           nullif(zuonr_ext_number, '') as zuonr_ext_number,
           nullif(zuonr_txt, '') as zuonr_txt,
           nullif(waers, '')  as waers,
           to_date(nullif(bldat, ''), 'YYYY-MM-DD') as bldat,
           nullif(xblnr, '')  as xblnr,
           nullif(bktxt, '')  as bktxt,
           to_date(nullif(budat, ''), 'YYYY-MM-DD') as budat,
           nullif(hkont, '')  as hkont,
           nullif(dmbtr, '')::float as dmbtr,
           nullif(wrbtr, '') ::float as wrbtr,
           to_date(nullif(zfbdt, ''), 'YYYY-MM-DD') as zfbdt,
           nullif(fistl, '') as fistl,
           nullif(zuonr, '') as zuonr,
           nullif(n_hkont, '') as n_hkont,
           nullif(n_fistl, '') as n_fistl,
           nullif(n_dir, '') as n_dir,
           nullif(vat_wrbtr, '')::float as vat_wrbtr,
           nullif(wrbtr_za, '')::float as wrbtr_za,
           nullif(vat_wrbtr_za, '')::float as vat_wrbtr_za,
           nullif(sgtxt, '')  as sgtxt,
           nullif(usl_plat, '') as usl_plat,
           regexp_replace(nullif(days_pay, ''), '\.', '', 'g')::float as days_pay,
           nullif(zterm, '')  as zterm,
           nullif(zterm_txt, '') as zterm_txt,
           nullif(sum15, '')::float as sum15,
           nullif(sum30, '')::float as sum30,
           nullif(sum60, '')::float as sum60,
           nullif(pay_stat, '') as pay_stat,
           nullif(sum_over, '')::float as sum_over,
           nullif(pay_txt_long, '') as pay_txt_long,
           nullif(usnam, '')  as usnam,
           nullif(rsd_bu_txt, '') as rsd_bu_txt,
           nullif(rsd_nu_txt, '') as rsd_nu_txt,
           nullif(rsd_bu_wrbtr, '')::float as rsd_bu_wrbtr,
           nullif(rsd_bu_dmbtr, '')::float as rsd_bu_dmbtr,
           nullif(rsd_nu_wrbtr, '')::float as rsd_nu_wrbtr,
           nullif(rsd_nu_dmbtr, '')::float as rsd_nu_dmbtr,
           to_date(nullif(zaldt, ''), 'YYYY-MM-DD') as zaldt,
           nullif(refin, '')::float as refin,
           rscdbsr.debit_or_credit as debit_or_credit
    from dwh_staging.raw_sap_credit_debit_bill_soap_response rscdbsr,
        xmltable('//ET_DATA/item' passing response_content columns
             p_stat varchar path 'P_STAT',
             bukrs varchar path 'BUKRS',
             buzei varchar path 'BUZEI',
             belnr varchar path 'BELNR',
             gjahr varchar path 'GJAHR',
             hdr_txt varchar path 'HDR_TXT',
             clr_belnr varchar path 'CLR_BELNR',
             bp_group varchar path 'BP_GROUP',
             n_bp_group varchar path 'N_BP_GROUP',
             partner varchar path 'PARTNER',
             n_partner varchar path 'N_PARTNER',
             zuonr_ext_date varchar path 'ZUONR_EXT_DATE',
             zuonr_int_number varchar path 'ZUONR_INT_NUMBER',
             zuonr_ext_number varchar path 'ZUONR_EXT_NUMBER',
             zuonr_txt varchar path 'ZUONR_TXT',
             waers varchar path 'WAERS',
             bldat varchar path 'BLDAT',
             xblnr varchar path 'XBLNR',
             bktxt varchar path 'BKTXT',
             budat varchar path 'BUDAT',
             hkont varchar path 'HKONT',
             dmbtr varchar path 'DMBTR',
             wrbtr varchar path 'WRBTR',
             zfbdt varchar path 'ZFBDT',
             fistl varchar path 'FISTL',
             zuonr varchar path 'ZUONR',
             n_hkont varchar path 'N_HKONT',
             n_fistl varchar path 'N_FISTL',
             n_dir varchar path 'N_DIR',
             vat_wrbtr varchar path 'VAT_WRBTR',
             wrbtr_za varchar path 'WRBTR_ZA',
             vat_wrbtr_za varchar path 'VAT_WRBTR_ZA',
             sgtxt varchar path 'SGTXT',
             usl_plat varchar path 'USL_PLAT',
             days_pay varchar path 'DAYS_PAY',
             zterm varchar path 'ZTERM',
             zterm_txt varchar path 'ZTERM_TXT',
             sum15 varchar path 'SUM15',
             sum30 varchar path 'SUM30',
             sum60 varchar path 'SUM60',
             pay_stat varchar path 'PAY_STAT',
             sum_over varchar path 'SUM_OVER',
             pay_txt_long varchar path 'PAY_TXT_LONG',
             usnam varchar path 'USNAM',
             rsd_bu_txt varchar path 'RSD_BU_TXT',
             rsd_nu_txt varchar path 'RSD_NU_TXT',
             rsd_bu_wrbtr varchar path 'RSD_BU_WRBTR',
             rsd_bu_dmbtr varchar path 'RSD_BU_DMBTR',
             rsd_nu_wrbtr varchar path 'RSD_NU_WRBTR',
             rsd_nu_dmbtr varchar path 'RSD_NU_DMBTR',
             zaldt varchar path 'ZALDT',
             refin varchar path 'REFIN');

    insert into dwh_presentation.report_debit_credit_bill
    select *
    from dwh_staging.report_debit_credit_bill;

end
$$;