create view dwh_presentation.ВертолетныеУслуги as
select
    flight_id as "Идентификатор полета",
    work_name_text as "Наименование вида работ",
    number_flight_task as "Номер полетного задания",
    flight_task_date as "Дата полетного задания",
    carrier_code as "Код перевозчика",
    carrier_name as "Название перевозчика",
    flight_number as "№ рейса",
    work_date as "Дата выполн. работ",
    request_number as "№ заявки",
    request_date as "Дата заявки",
    customer_code as "Заказчик",
    customer_name as "Наименование заказчика",
    customer_subdivision_code as "Подразделение заказчика",
    customer_subdivision_name as "Наименование подразделения заказчика",
    contract as "Контракт",
    contract_date_from_card as "Номер/дата договора из карточки",
    direction "Дирекция",
    aircraft as "Воздушное судно",
    aircraft_type as "Тип воздушного судна",
    aircraft_owner_code as "Эксплуатант",
    aircraft_owner_txt as "Наименование владельца ВС",
    board_act as "Воздушное судно по акту",
    board_type_act as "Тип ВС по акту",
    ground_time as "Земля, время",
    ground_count as "Земля, количество",
    air_time as "Факт, время",
    air_count as "Факт, количество",
    sum_time as "Сумма Факт, время",
    sum_count as "Сумма Факт, количество",
    non_prod_flight_type as "НаимТипаНепроизвНалёта",
    non_prod_flight_time as "Время непроизводственного налёта",
    non_prod_flight_count as "Непроизводственный налёт, Количество",
    act_time as "Акт, время",
    act_count as "Акт, количество",
    act_sum_time as "Сумма Акт, время",
    act_sum_count as "Сумма Акт, количество",
    order_number as "№ Заказа",
    full_material_name as "Полное наименование материала",
    sum_without_nds as "Сумма без НДС",
    sum_with_nds as "Сумма НДС",
    accuracy as "Погрешность",F
    task_number_act as "№ заказа, акт",
    facture_number as "№ фактуры",
    facture_number_act as "№ фактуры, акт",
    delta_flight as "РазницаВС",
    delta_fact_act as "РазницаФакт/Акт",
    flight_litera as "Литера рейса",
    city_code_work as "Место проведения работ",
    city_text_work as "Наименование места проведения работ",
    currency as "ВалютаДокумента",
    unit as "Единица измерения",
    external_invoice_number as "Внешний номер счета-фактуры",
    document_date as "Дата документа",
    comments_text as "Примечание",
    creator_name as "Создал"
from dwh_presentation.report_zutvuF;

alter view dwh_presentation.ВертолетныеУслуги owner to dwh;
grant select on dwh_presentation.ВертолетныеУслуги to readonly;