drop table dwh_presentation.fact_leg;

create table dwh_presentation.fact_leg
(
    id serial,
	md5_flight varchar,
	md5_leg varchar,
	id_date integer,
	id_time integer,
	id_flight integer,
	id_board integer,
	id_origin integer,
	id_destination integer,
	source_code varchar,
	source varchar,
	flight_date timestamp,
	actual_date timestamp,
	delay_codes varchar,
	departure_plan_local timestamp,
	departure_plan_utc timestamp,
	arrival_plan_local timestamp,
	arrival_plan_utc timestamp,
	departure_est_local timestamp,
	departure_est_utc timestamp,
	arrival_est_local timestamp,
	arrival_est_utc timestamp,
	departure_fact_local timestamp,
	departure_fact_utc timestamp,
	arrival_fact_local timestamp,
	arrival_fact_utc timestamp,
	power_on timestamp,
	power_off timestamp,
	on_surface varchar,
	pax_transit integer,
	f_nr integer,
	c_nr integer,
	y_nr integer,
	child_nr integer,
	infant_nr integer,
	crg_load integer,
	luggage_load integer,
	hand_luggage integer,
	mail_load integer,
	cabin_baggage integer,
	emptying integer,
	fueling integer,
	dep_remnant integer,
	arr_remnant integer,
	f_seats_occupied integer,
	c_seats_occupied integer,
	y_seats_occupied integer,
	f_seats_total integer,
	c_seats_total integer,
	y_seats_total integer,
	payload integer,
	f_child integer,
	c_child integer,
	y_child integer,
	f_infant integer,
	c_infant integer,
	y_infant integer,
	distance integer,
	equipped_empty_kg integer,
	flight_task varchar,
	external_flight_id integer,
	fuel_qty_on_flight_record_start float,
	fuel_qty_on_flight_record_finish float,
	aircraft_weight_pounds_start_record float,
	aircraft_weight_pounds_finish_record float,
	aircraft_weight_tons_start_record float,
	aircraft_weight_tons_finish_record float,
	aircraft_weight_without_fuel_tons_start_record float,
	aircraft_weight_without_fuel_tons_finish_record float
);

alter table dwh_presentation.fact_leg owner to dwh;
grant select on dwh_presentation.fact_leg to readonly;
