create or replace view dwh_presentation.v_report_zut_bill as
select
    sales_channel_code as "Канал сбыта",
    sales_channel_name as "Наименование канала сбыта",
    trade_doc as "Торговый документ",
    external_invoice_num as "Внешний номер счета-фактуры",
    sales_doc_pos as "Позиция документа",
    sales_doc as "№ документа",
    sales_organization_name as "Название сбытовой организации",
    fp_order_code as "ФП заказа",
    fp_order_name as "Название ФП заказа",
    fp_accounting_doc_code as "ФП бухдокумента",
    fp_accounting_doc_name as "Название ФП бух.документа",
    material_number as "Материал",
    material_group_name as "Наименование группы материалов",
    sales_dept_name as "Наименование отдела сбыта",
    airport_oirg_name as "Наименование аэропорта вылета",
    aircraft_act_type as "Тип воздушного судна по акту",
    aircraft_type as "Тип воздушного судна",
    aircraft as "Воздушное судно",
    owner_code as "Эксплуатант",
    owner_name as "Наименование владельца ВС",
    order_number as "Номер договора",
    order_number_external as "Внешний номер договора",
    actual_invoiced_quantity as "ФактурКоличество",
    selling_mu as "ПродажнЕдиница",
    net_price as "Цена нетто",
    net_currency_doc_curr as "Стоимость нетто(позиция)",
    customer_code as "Заказчик",
    customer_name as "Наименование заказчика",
    payer_name as "Наименование плательщика",
    doc_executor_name as "Создал",
    client_sales_text as "Текст позиции заказа",
    works_services_completion_date as "Дата выполн. работ",
    flight_task_date as "Дата полетного задания",
    record_created_date as "Дата создания",
    sales_doc_curr as "ВалютаДокумента",
    exchange_rate_for_fi_postings as "Валютный курс",
    reversed_invoice_number as "Сторнирована",
    flight_task_number as "Номер полетного задания",
    invoice_kind_code as "Вид фактуры",
    material_recipient_name as "Наименование грузополучателя",
    city_name as "Наименование МПР",
    company_group as "Группа компаний",
    company_group_name as "Наименование группы компаний"
from dwh_presentation.report_zut_bill;

alter view dwh_presentation.v_report_zut_bill owner to dwh;
grant select on dwh_presentation.v_report_zut_bill to readonly;