create or replace function dwh_staging.sf_prepare_sap_zutvu()
    returns void
    language plpgsql
as
$$
begin
    truncate table dwh_staging.report_zutvu;
    truncate table dwh_presentation.report_zutvu;

    insert into dwh_staging.report_zutvu(
        wknam__work_name_text, number__number_flight_task, date__flight_task_date, carrier__carrier_code, 
        carrier_txt__carrier_name, bstkd_e__flight_number,litera__flight_litera, fbuda__work_date, bstkd__request_number,
        bstdk__request_date, customer__customer_code, customer_name__customer_name,
        customer_unit__customer_subdivision_code, customer_unit_name__customer_subdivision_name, contract__contract,
        external_contract__contract_date_from_card, vkbur__direction, aircraft__aircraft, aircraft_type__aircraft_type,
        aircraft_owner__aircraft_owner_code, aircraft_owner_txt__aircraft_owner_txt, airct_c__board_act, 
        airct_type_c__board_type_act, zzcitya_alv__city_code_work, zzcitya_alv_txt__city_text_work, eartim__ground_time, 
        earmng__ground_count, airtim__air_time, airmng__air_count, sumtim__sum_time, summng__sum_count,
        typnp_txt__non_prod_flight_type, nptim__non_prod_flight_time, npmng__non_prod_flight_count, actdur__act_time, 
        actmng__act_count, sum_actdur__act_sum_time, sum_actmng__act_sum_count, order__order_number,
        matxt__full_material_name, summa__sum_without_nds, nds_sum__with_nds, sum_diff__accuracy, waerk__currency, 
        order_act_c__task_number_act, vbeln_vf__facture_number, vbeln_vf_c__facture_number_act, zieme__unit,
        fltid__flight_id, zzextnum__external_invoice_number, bldat__document_date, comments__comments, 
        delta_aircttype__delta_flight, delta_acttime__delta_fact_act, uname__creator_name)
    select 
        nullif(wknam, '') as wknam,
        nullif(number, '') as number,
        to_date(nullif(flight_task_date, '0000-00-00'), 'YYYY-MM-DD') as flight_task_date,
        nullif(carrier, '') as carrier,
        nullif(carrier_txt, '') as carrier_txt,
        nullif(bstkd_e, '') as bstkd_e,
        nullif(litera, '') as litera,
        nullif(fbuda, '0000-00-00')::date as fbuda,
        nullif(bstkd, '') as bstkd,
        nullif(bstdk, '0000-00-00')::date as bstdk,
        nullif(customer, '') as customer,
        nullif(customer_name, '') as customer_name,
        nullif(customer_unit, '') as customer_unit,
        nullif(customer_unit_name, '') as customer_unit_name,
        nullif(contract, '') as contract,
        nullif(external_contract, '') as external_contract,
        regexp_replace(vkbur, '', null)::int as vkbur,
        nullif(aircraft, '') as aircraft,
        nullif(aircraft_type, '') as aircraft_type,
        nullif(aircraft_owner, '') as aircraft_owner,
        nullif(aircraft_owner_txt, '') as aircraft_owner_txt,
        nullif(airct_c, '') as airct_c,
        nullif(airct_type_c, '') as airct_type_c,
        nullif(zzcitya_alv, '') as zzcitya_alv,
        nullif(zzcitya_alv_txt, '') as zzcitya_alv_txt,
        eartim as eartim,
        nullif(earmng, '0.0')::float as earmng,
        airtim as airtim,
        nullif(airmng, '0.0')::float as airmng,
        sumtim as sumtim,
        nullif(summng, '0.0')::float as summng,
        nullif(typnp_txt, '') as typnp_txt,
        nptim  as nptim,
        nullif(npmng, '0.0')::float as npmng,
        actdur as actdur,
        nullif(actmng, '0.0')::float as actmng,
        sum_actdur    as sum_actdur,
        nullif(sum_actmng, '0.0')::float as sum_actmng,
        nullif(order_num, '') as order_num,
        nullif(matxt, '') as matxt,
        nullif(summa, '0.0')::float as summa,
        nullif(nds, '0.0')::float as nds,
        nullif(sum_diff, '0.0')::float as sum_diff,
        nullif(waerk, '') as waerk,
        nullif(order_act_c, '') as order_act_c,
        nullif(vbeln_vf, '') as vbeln_vf,
        nullif(vbeln_vf_c, '') as vbeln_vf_c,
        nullif(zieme, '') as zieme,
        regexp_replace(fltid, '', null)::int as fltid,
        nullif(zzextnum, '') as zzextnum,
        nullif(bldat, '') as bldat,
        nullif(comments_txt, '') as comments_txt,
        nullif(delta_aircttype, '') as delta_aircttype,
        nullif(delta_acttime, '') as delta_acttime,
        nullif(uname, '') as uname
    from dwh_staging.raw_sap_zutvu_soap_response,
        xmltable('//ET_DATA/item' passing response_content columns
            wknam varchar path 'WKNAM',
            number varchar path 'NUMBER',
            flight_task_date varchar path 'DATE',
            carrier varchar path 'CARRIER',
            carrier_txt varchar path 'CARRIER_TXT',
            bstkd_e varchar path 'BSTKD_E',
            litera varchar path 'LITERA',
            fbuda varchar path 'FBUDA',
            bstkd varchar path 'BSTKD',
            bstdk varchar path 'BSTDK',
            customer varchar path 'CUSTOMER',
            customer_name varchar path 'CUSTOMER_NAME',
            customer_unit varchar path 'CUSTOMER_UNIT',
            customer_unit_name varchar path 'CUSTOMER_UNIT_NAME',
            contract varchar path 'CONTRACT',
            external_contract varchar path 'EXTERNAL_CONTRACT',
            vkbur varchar path 'VKBUR',
            aircraft varchar path 'AIRCRAFT',
            aircraft_type varchar path 'AIRCRAFT_TYPE',
            aircraft_owner varchar path 'AIRCRAFT_OWNER',
            aircraft_owner_txt varchar path 'AIRCRAFT_OWNER_TXT',
            airct_c varchar path 'AIRCT_C',
            airct_type_c varchar path 'AIRCT_TYPE_C',
            zzcitya_alv varchar path 'ZZCITYA_ALV',
            zzcitya_alv_txt varchar path 'ZZCITYA_ALV_TXT',
            eartim varchar path 'EARTIM',
            earmng varchar path 'EARMNG',
            airtim varchar path 'AIRTIM',
            airmng varchar path 'AIRMNG',
            sumtim varchar path 'SUMTIM',
            summng varchar path 'SUMMNG',
            typnp_txt varchar path 'TYPNP_TXT',
            nptim varchar path 'NPTIM',
            npmng varchar path 'NPMNG',
            actdur varchar path 'ACTDUR',
            actmng varchar path 'ACTMNG',
            sum_actdur varchar path 'SUM_ACTDUR',
            sum_actmng varchar path 'SUM_ACTMNG',
            order_num varchar path 'ORDER',
            matxt varchar path 'MATXT',
            summa varchar path 'SUMMA',
            nds varchar path 'NDS',
            sum_diff varchar path 'SUM_DIFF',
            waerk varchar path 'WAERK',
            order_act_c varchar path 'ORDER_ACT_C',
            vbeln_vf varchar path 'VBELN_VF',
            vbeln_vf_c varchar path 'VBELN_VF_C',
            zieme varchar path 'ZIEME',
            fltid varchar path 'FLTID',
            zzextnum varchar path 'ZZEXTNUM',
            bldat varchar path 'BLDAT',
            comments_txt varchar path 'COMMENTS',
            delta_aircttype varchar path 'DELTA_AIRCTTYPE',
            delta_acttime varchar path 'DELTA_ACTTIME',
            uname varchar path 'UNAME');

    insert into dwh_presentation.report_zutvu
    select 
        fltid__flight_id,
        wknam__work_name_text,
        number__number_flight_task,
        date__flight_task_date,
        carrier__carrier_code,
        carrier_txt__carrier_name,
        bstkd_e__flight_number,
        fbuda__work_date,
        bstkd__request_number,
        bstdk__request_date,
        customer__customer_code,
        customer_name__customer_name,
        customer_unit__customer_subdivision_code,
        customer_unit_name__customer_subdivision_name,
        contract__contract,
        external_contract__contract_date_from_card,
        vkbur__direction,
        aircraft__aircraft,
        aircraft_type__aircraft_type,
        aircraft_owner__aircraft_owner_code,
        aircraft_owner_txt__aircraft_owner_txt,
        airct_c__board_act,
        airct_type_c__board_type_act,
        eartim__ground_time,
        earmng__ground_count,
        airtim__air_time,
        airmng__air_count,
        sumtim__sum_time,
        summng__sum_count,
        typnp_txt__non_prod_flight_type,
        nptim__non_prod_flight_time,
        npmng__non_prod_flight_count,
        actdur__act_time,
        actmng__act_count,
        sum_actdur__act_sum_time,
        actmng__act_count,
        order__order_number,
        matxt__full_material_name,
        summa__sum_without_nds,
        nds_sum__with_nds,
        sum_diff__accuracy,
        order_act_c__task_number_act,
        vbeln_vf__facture_number,
        vbeln_vf_c__facture_number_act,
        delta_aircttype__delta_flight,
        delta_acttime__delta_fact_act,
        litera__flight_litera,
        zzcitya_alv__city_code_work,
        zzcitya_alv_txt__city_text_work,
        waerk__currency,
        zieme__unit,
        zzextnum__external_invoice_number,
        bldat__document_date,
        comments__comments,
        uname__creator_name
    FROM dwh_staging.report_zutvu;
end
$$;